[options]
addons_path = C:/Users/orega/odoo18-dev/odoo18/addons,C:/Users/orega/Documents/GitHub/Retail/addons
db_host = localhost
db_port = 5433
db_user = odoo
db_password = False
http_port = 8070
log_level = info
list_db = True
without_demo = False
